/* MITRE ATT&CK (Enterprise) reference, offline subset — identical to the prototype's table
   so existing case files keep their tactic/technique ids and colours. */

export interface Tactic {
  id: string;
  name: string;
  short: string;
  color: string;
  tech: ReadonlyArray<readonly [string, string]>;
}

export const TACTICS: readonly Tactic[] = [
  {
    id: 'TA0043',
    name: 'Reconnaissance',
    short: 'RECON',
    color: '#5b8dff',
    tech: [
      ['T1595', 'Active Scanning'],
      ['T1595.002', 'Vulnerability Scanning'],
      ['T1592', 'Gather Victim Host Info'],
      ['T1589', 'Gather Victim Identity Info'],
      ['T1590', 'Gather Victim Network Info'],
      ['T1598', 'Phishing for Information'],
      ['T1596', 'Search Open Technical Databases'],
      ['T1593', 'Search Open Websites/Domains'],
    ],
  },
  {
    id: 'TA0042',
    name: 'Resource Development',
    short: 'RESDEV',
    color: '#4f6dd6',
    tech: [
      ['T1583', 'Acquire Infrastructure'],
      ['T1583.001', 'Domains'],
      ['T1584', 'Compromise Infrastructure'],
      ['T1587', 'Develop Capabilities'],
      ['T1588', 'Obtain Capabilities'],
      ['T1588.002', 'Tool'],
      ['T1585', 'Establish Accounts'],
      ['T1608', 'Stage Capabilities'],
    ],
  },
  {
    id: 'TA0001',
    name: 'Initial Access',
    short: 'INIT',
    color: '#ff2e88',
    tech: [
      ['T1566', 'Phishing'],
      ['T1566.001', 'Spearphishing Attachment'],
      ['T1566.002', 'Spearphishing Link'],
      ['T1190', 'Exploit Public-Facing Application'],
      ['T1133', 'External Remote Services'],
      ['T1078', 'Valid Accounts'],
      ['T1078.002', 'Domain Accounts'],
      ['T1078.003', 'Local Accounts'],
      ['T1195', 'Supply Chain Compromise'],
      ['T1189', 'Drive-by Compromise'],
      ['T1091', 'Replication Through Removable Media'],
      ['T1200', 'Hardware Additions'],
    ],
  },
  {
    id: 'TA0002',
    name: 'Execution',
    short: 'EXEC',
    color: '#ff6b3d',
    tech: [
      ['T1059', 'Command and Scripting Interpreter'],
      ['T1059.001', 'PowerShell'],
      ['T1059.003', 'Windows Command Shell'],
      ['T1059.004', 'Unix Shell'],
      ['T1059.005', 'Visual Basic'],
      ['T1059.006', 'Python'],
      ['T1059.007', 'JavaScript'],
      ['T1204', 'User Execution'],
      ['T1204.002', 'Malicious File'],
      ['T1047', 'Windows Management Instrumentation'],
      ['T1053', 'Scheduled Task/Job'],
      ['T1053.005', 'Scheduled Task'],
      ['T1569', 'System Services'],
      ['T1569.002', 'Service Execution'],
      ['T1106', 'Native API'],
      ['T1203', 'Exploitation for Client Execution'],
      ['T1129', 'Shared Modules'],
    ],
  },
  {
    id: 'TA0003',
    name: 'Persistence',
    short: 'PERSIST',
    color: '#ffb020',
    tech: [
      ['T1547', 'Boot or Logon Autostart Execution'],
      ['T1547.001', 'Registry Run Keys / Startup Folder'],
      ['T1543', 'Create or Modify System Process'],
      ['T1543.003', 'Windows Service'],
      ['T1053.005', 'Scheduled Task'],
      ['T1136', 'Create Account'],
      ['T1136.001', 'Local Account'],
      ['T1136.002', 'Domain Account'],
      ['T1078', 'Valid Accounts'],
      ['T1505', 'Server Software Component'],
      ['T1505.003', 'Web Shell'],
      ['T1546', 'Event Triggered Execution'],
      ['T1546.003', 'WMI Event Subscription'],
      ['T1098', 'Account Manipulation'],
      ['T1574', 'Hijack Execution Flow'],
      ['T1197', 'BITS Jobs'],
      ['T1556', 'Modify Authentication Process'],
    ],
  },
  {
    id: 'TA0004',
    name: 'Privilege Escalation',
    short: 'PRIVESC',
    color: '#ff4d5e',
    tech: [
      ['T1548', 'Abuse Elevation Control Mechanism'],
      ['T1548.002', 'Bypass User Account Control'],
      ['T1134', 'Access Token Manipulation'],
      ['T1068', 'Exploitation for Privilege Escalation'],
      ['T1055', 'Process Injection'],
      ['T1484', 'Domain or Tenant Policy Modification'],
      ['T1484.001', 'Group Policy Modification'],
      ['T1078', 'Valid Accounts'],
      ['T1543.003', 'Windows Service'],
    ],
  },
  {
    id: 'TA0005',
    name: 'Defense Evasion',
    short: 'EVADE',
    color: '#9d6bff',
    tech: [
      ['T1070', 'Indicator Removal'],
      ['T1070.001', 'Clear Windows Event Logs'],
      ['T1070.004', 'File Deletion'],
      ['T1070.006', 'Timestomp'],
      ['T1027', 'Obfuscated Files or Information'],
      ['T1027.010', 'Command Obfuscation'],
      ['T1562', 'Impair Defenses'],
      ['T1562.001', 'Disable or Modify Tools'],
      ['T1562.004', 'Disable or Modify System Firewall'],
      ['T1055', 'Process Injection'],
      ['T1218', 'System Binary Proxy Execution'],
      ['T1218.005', 'Mshta'],
      ['T1218.010', 'Regsvr32'],
      ['T1218.011', 'Rundll32'],
      ['T1036', 'Masquerading'],
      ['T1112', 'Modify Registry'],
      ['T1140', 'Deobfuscate/Decode Files or Information'],
      ['T1553', 'Subvert Trust Controls'],
      ['T1497', 'Virtualization/Sandbox Evasion'],
      ['T1620', 'Reflective Code Loading'],
      ['T1207', 'Rogue Domain Controller'],
      ['T1550', 'Use Alternate Authentication Material'],
    ],
  },
  {
    id: 'TA0006',
    name: 'Credential Access',
    short: 'CREDS',
    color: '#22e8ff',
    tech: [
      ['T1003', 'OS Credential Dumping'],
      ['T1003.001', 'LSASS Memory'],
      ['T1003.002', 'Security Account Manager'],
      ['T1003.003', 'NTDS'],
      ['T1003.006', 'DCSync'],
      ['T1110', 'Brute Force'],
      ['T1110.003', 'Password Spraying'],
      ['T1558', 'Steal or Forge Kerberos Tickets'],
      ['T1558.001', 'Golden Ticket'],
      ['T1558.002', 'Silver Ticket'],
      ['T1558.003', 'Kerberoasting'],
      ['T1558.004', 'AS-REP Roasting'],
      ['T1555', 'Credentials from Password Stores'],
      ['T1555.003', 'Credentials from Web Browsers'],
      ['T1552', 'Unsecured Credentials'],
      ['T1552.001', 'Credentials In Files'],
      ['T1056', 'Input Capture'],
      ['T1056.001', 'Keylogging'],
      ['T1187', 'Forced Authentication'],
      ['T1557', 'Adversary-in-the-Middle'],
      ['T1557.001', 'LLMNR/NBT-NS Poisoning and SMB Relay'],
      ['T1621', 'Multi-Factor Authentication Request Generation'],
    ],
  },
  {
    id: 'TA0007',
    name: 'Discovery',
    short: 'DISCOVER',
    color: '#4dff9a',
    tech: [
      ['T1087', 'Account Discovery'],
      ['T1087.002', 'Domain Account'],
      ['T1082', 'System Information Discovery'],
      ['T1083', 'File and Directory Discovery'],
      ['T1018', 'Remote System Discovery'],
      ['T1046', 'Network Service Discovery'],
      ['T1057', 'Process Discovery'],
      ['T1016', 'System Network Configuration Discovery'],
      ['T1049', 'System Network Connections Discovery'],
      ['T1069', 'Permission Groups Discovery'],
      ['T1069.002', 'Domain Groups'],
      ['T1482', 'Domain Trust Discovery'],
      ['T1033', 'System Owner/User Discovery'],
      ['T1518', 'Software Discovery'],
      ['T1518.001', 'Security Software Discovery'],
      ['T1135', 'Network Share Discovery'],
      ['T1201', 'Password Policy Discovery'],
    ],
  },
  {
    id: 'TA0008',
    name: 'Lateral Movement',
    short: 'LATERAL',
    color: '#00d1b8',
    tech: [
      ['T1021', 'Remote Services'],
      ['T1021.001', 'Remote Desktop Protocol'],
      ['T1021.002', 'SMB/Windows Admin Shares'],
      ['T1021.004', 'SSH'],
      ['T1021.006', 'Windows Remote Management'],
      ['T1570', 'Lateral Tool Transfer'],
      ['T1550', 'Use Alternate Authentication Material'],
      ['T1550.002', 'Pass the Hash'],
      ['T1550.003', 'Pass the Ticket'],
      ['T1210', 'Exploitation of Remote Services'],
      ['T1080', 'Taint Shared Content'],
      ['T1563', 'Remote Service Session Hijacking'],
      ['T1072', 'Software Deployment Tools'],
    ],
  },
  {
    id: 'TA0009',
    name: 'Collection',
    short: 'COLLECT',
    color: '#a0d911',
    tech: [
      ['T1005', 'Data from Local System'],
      ['T1039', 'Data from Network Shared Drive'],
      ['T1074', 'Data Staged'],
      ['T1074.001', 'Local Data Staging'],
      ['T1074.002', 'Remote Data Staging'],
      ['T1560', 'Archive Collected Data'],
      ['T1560.001', 'Archive via Utility'],
      ['T1113', 'Screen Capture'],
      ['T1114', 'Email Collection'],
      ['T1056.001', 'Keylogging'],
      ['T1119', 'Automated Collection'],
      ['T1213', 'Data from Information Repositories'],
    ],
  },
  {
    id: 'TA0011',
    name: 'Command and Control',
    short: 'C2',
    color: '#ff2ed4',
    tech: [
      ['T1071', 'Application Layer Protocol'],
      ['T1071.001', 'Web Protocols'],
      ['T1071.004', 'DNS'],
      ['T1105', 'Ingress Tool Transfer'],
      ['T1573', 'Encrypted Channel'],
      ['T1573.002', 'Asymmetric Cryptography'],
      ['T1090', 'Proxy'],
      ['T1090.003', 'Multi-hop Proxy'],
      ['T1219', 'Remote Access Software'],
      ['T1572', 'Protocol Tunneling'],
      ['T1568', 'Dynamic Resolution'],
      ['T1568.002', 'Domain Generation Algorithms'],
      ['T1102', 'Web Service'],
      ['T1095', 'Non-Application Layer Protocol'],
      ['T1008', 'Fallback Channels'],
      ['T1132', 'Data Encoding'],
    ],
  },
  {
    id: 'TA0010',
    name: 'Exfiltration',
    short: 'EXFIL',
    color: '#ff8c00',
    tech: [
      ['T1041', 'Exfiltration Over C2 Channel'],
      ['T1048', 'Exfiltration Over Alternative Protocol'],
      ['T1048.003', 'Exfiltration Over Unencrypted Non-C2 Protocol'],
      ['T1567', 'Exfiltration Over Web Service'],
      ['T1567.002', 'Exfiltration to Cloud Storage'],
      ['T1029', 'Scheduled Transfer'],
      ['T1030', 'Data Transfer Size Limits'],
      ['T1052', 'Exfiltration Over Physical Medium'],
      ['T1011', 'Exfiltration Over Other Network Medium'],
    ],
  },
  {
    id: 'TA0040',
    name: 'Impact',
    short: 'IMPACT',
    color: '#ff1f3d',
    tech: [
      ['T1486', 'Data Encrypted for Impact'],
      ['T1490', 'Inhibit System Recovery'],
      ['T1489', 'Service Stop'],
      ['T1485', 'Data Destruction'],
      ['T1491', 'Defacement'],
      ['T1498', 'Network Denial of Service'],
      ['T1499', 'Endpoint Denial of Service'],
      ['T1531', 'Account Access Removal'],
      ['T1565', 'Data Manipulation'],
      ['T1496', 'Resource Hijacking'],
      ['T1561', 'Disk Wipe'],
      ['T1657', 'Financial Theft'],
    ],
  },
];

export const TACTIC_BY_ID: Readonly<Record<string, Tactic>> = Object.fromEntries(
  TACTICS.map((t) => [t.id, t]),
);
export const TECHNIQUE_NAME: Readonly<Record<string, string>> = Object.fromEntries(
  TACTICS.flatMap((t) => t.tech.map(([id, name]) => [id, name])),
);

export const IOC_TYPES = [
  'ip',
  'domain',
  'url',
  'sha256',
  'sha1',
  'md5',
  'filepath',
  'filename',
  'registry',
  'email',
  'useraccount',
  'process',
  'service',
  'mutex',
  'port',
  'cve',
  'certificate',
  'user-agent',
  'other',
] as const;

export const PRIVS = [
  'standard user',
  'local admin',
  'domain user',
  'domain admin',
  'enterprise admin',
  'SYSTEM',
  'service account',
  'root',
  'sudo',
  'machine account',
  'unknown',
] as const;

export interface Labelled<T extends string> {
  id: T;
  label: string;
  color: string;
}

export const CONFIDENCE: readonly Labelled<
  'confirmed' | 'high' | 'medium' | 'low' | 'suspected'
>[] = [
  { id: 'confirmed', label: 'Confirmed', color: '#4dff9a' },
  { id: 'high', label: 'High', color: '#22e8ff' },
  { id: 'medium', label: 'Medium', color: '#ffb020' },
  { id: 'low', label: 'Low', color: '#9d6bff' },
  { id: 'suspected', label: 'Suspected', color: '#6d8299' },
];

export const SEVERITY: readonly Labelled<'critical' | 'high' | 'medium' | 'low' | 'info'>[] = [
  { id: 'critical', label: 'Critical', color: '#ff1f3d' },
  { id: 'high', label: 'High', color: '#ff6b3d' },
  { id: 'medium', label: 'Medium', color: '#ffb020' },
  { id: 'low', label: 'Low', color: '#22e8ff' },
  { id: 'info', label: 'Info', color: '#6d8299' },
];

export const HOST_STATUS: readonly Labelled<
  'compromised' | 'suspect' | 'contained' | 'remediated' | 'clean' | 'unknown'
>[] = [
  { id: 'compromised', label: 'Compromised', color: '#ff1f3d' },
  { id: 'suspect', label: 'Suspect', color: '#ffb020' },
  { id: 'contained', label: 'Contained', color: '#9d6bff' },
  { id: 'remediated', label: 'Remediated', color: '#4dff9a' },
  { id: 'clean', label: 'Clean', color: '#22e8ff' },
  { id: 'unknown', label: 'Unknown', color: '#6d8299' },
];

export const CRITICALITY = ['crown jewel', 'high', 'moderate', 'low'] as const;

export const DATA_SOURCES = [
  'EDR',
  'Splunk',
  'Microsoft Sentinel',
  'Elastic',
  'QRadar',
  'Chronicle',
  'Windows Event Log',
  'Sysmon',
  'Firewall',
  'Proxy',
  'Zeek',
  'NetFlow',
  'DNS logs',
  'Email gateway',
  'Cloud audit log',
  'VPN log',
  'Memory image',
  'Disk image',
  'MFT',
  'Prefetch',
  'Registry hive',
  'Interview',
  'Other',
] as const;

export const LANE_COLORS = [
  '#22e8ff',
  '#ff2e88',
  '#4dff9a',
  '#ffb020',
  '#9d6bff',
  '#00d1b8',
  '#ff6b3d',
  '#5b8dff',
  '#ff2ed4',
  '#a0d911',
  '#ff4d5e',
  '#00a6ff',
] as const;

export const byId = <T extends string>(
  list: readonly Labelled<T>[],
): Readonly<Record<T, Labelled<T>>> =>
  Object.fromEntries(list.map((x) => [x.id, x])) as Record<T, Labelled<T>>;
